[package]
name = "sophus-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assertables = "7.0.1"
num-traits = "0.2.15"
nalgebra = "0.32"
approx = "0.5.1"
ndarray = "0.15.4"
notan =  { version = "0.9", features = ["egui"] }
egui = "0.21" 
tuple_list = "0.1.3"
linked-hash-map = "0.5.4"
enum_dispatch = "0.3.6"
hyperdual = "1.2.0"



[dev-dependencies.proptest]
version =  "1.1.0"
default-features = false
features = ["std"]

