name: main
on:
  push:
    branches: [main]
  pull_request:

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04

    steps: 
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      - name: maturin
        run: |
          cd py
          python3 -m venv .env
          source .env/bin/activate
          pip3 install maturin numpy
          maturin develop
          python3 -m test


